language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python3 manage.py makemigrations
- python3 manage.py migrate
- python3 manage.py test
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: hD4uoeu379f5MsTbaetT+pPr+ZykTJgErg94pQfC6Zf1USs+TzXaQuxGoXiozCZnlNJlPOFDeXCZZhqUoHGaCl4BihDYU1SqkuLZyzKsXN3O9Usz+9/fHVRbfolnYc1s0q9rnwyurkg6DebPMcLOgAEq6RojskYi+dop2im4D5cbdPQt2R9Ht8Xo7SuZSPt0OX22fPAAMtMWjmprSuNsMHni6mZmhpnov0DV6f4fpnYzdZdzM72MQ8B1k+aOaznayiDWO6lI8N0XbIiISvqADRXUseHRdR1/+9OePr1/Tp6j1qZZdwzEKTsp7/2t0LowO1eOYSQNuo7YZDJL+cT8X+uQYU8d3ZDriXEHgDm9ZqvjXjfvCamSRW1pQi5M17M9pEa1hOZucp4TvDkvTa9ONWFCEi2yPwpBuBFIYqjdIXuXh7JzeojtMf6dPG6XKED/J+vb/si2cpzjTzizyRgMNeZHvJqICYDvZytL3/wt8u42NcugMv+4Fu52qyHpimJTcqDCw6lOC64Xb+3CvwEqHgpv+0SNiNDeDB9gN1UIcspyvcFr6kVraMbtGDzxo/xuwn7GM9Q7dD872t/NGoWrHiUYWKSg4U8lEDS1k5hgDDbBW1sTDYROCsvAhAtM9XBZaXbghmyazvnuo5W9KLbZOieblOtpF8IUPAgpVGuRR10=
