language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python3 manage.py makemigrations
- python3 manage.py migrate
- python3 manage.py test
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: HRpSipa7trbpnI1fQPPcA38CFY2H5z5WGp4EBY0mBopsSVBUR5Uz5nh7fQ5a3ZdKoTEBA3HWIsKimR6nyzvfcgnSdXVB41TbFrGDe8Xm2cSGaaGbIcUCno7bVPsWqg7CGodnhBvxC6GyZFwnx09Rl7hfFGFhIu2W+wlCzFfp43J4ZD4ruh57hBoQ7NHtxysPgv7ikTpuvkQr3hg2eaWO6CkDCXHl6bB9DLQUOEpBJxMM5SCy79gzv6yHolll4UNOCbtoKjG257Baalrey6t5wJtaqeC6vUzdRGx1qxRk0ClsAg2jlvWIpE5xSkZX4Klxq9kXxDZbMzSYs90c7w+Ywg50bohzDxCjesLPHpIuSqlsfOQ85vjdXwFngWAzsVjTyqCKc0KfPI7f5ZgVjDA2uZMIzOukCQNwEttYprWYhLnhhsnyStG5xiWDDaraNXugBz1qG0oMEPRtJY47Wb+VljoOPjKYimOmkKdZLFIYHF3dQOJRjOqP+iXRpBu12DuY3Ir9xGA7wbfwMrdFiJucyFBVkWx/lbiJnV+KlBfAcVqaGhXyZ0jxnYgtlrHLFTDDwRyHTVa8TfaCs7a4jMJbIQjqmSm4aZKVwVum510R5UGG/o4VwEZ+TFiekmINGmPGHB+AGtqCtNAfYA4VWMBKyCDIZxvTEUlj8vIgOfFDjuU=
