language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - python3 manage.py test
branches:
  only:
    - master
deploy:
  api_key:
    secure: exiNYrI5kJRCwIgJGklQX++U9ajBlsAz1Ufc1EM+WlDN0AMxHjFrql06bP+uy9MDA0XDJG/qeNCqlZp7BjK+i08b5h+S70WltDgG30sSqltbKwNRVA1yzjVkNN5FGG+dth2L9ni+QFRNd9JLFQxFJ36KCWdPJpQ2ZofWiCLNlJSa4jYdXdGfkBsUXKtDn15haXAfsSnGeAtMSmA2Ij1C79FCeoOznHlUD+yvj1qU8ewAKKS+Wr7AXRHfa2tymkdfIIpLs8rGMXn0cdN/pBjs6RO53dKSezJ1s16F44kMRYKZOS86PgMabcQbYYHZKvLDTU3Trgkxm/OQ4EbPJaUeDjLfmVPQA9DWrgKb13rkcwXGHJeTA+MMuyea2gLgLagx7nzrgJ0iXD4u6fKpD03M6tu+leU8WCKFsNEUMp7ipt0U4HHmb5H31XCv1uGfRK2ICj6+dCH+NrDd4WM9zWYHsGaVC6ItkvDroJNCluwvIND8pa5madGoAz5v2rvzJrNVlYYeVnoJFfzmUOIglj5MFtpnAOJuR8SAGR4qGwZvkhoVYRNcNZmaN33u6gDkkQKr7bvobn/LkZON38+5J1wyMP/zBKWlNrjizNG9u3n6IGojL/bGnWEyBU+S3O1vIyDGajMaG/ZF3UvpuTY+IEDA3qK60IHOJQ8GoBXe4laFgpI=
